# -*- coding: utf-8 -*-
"""Python Contact Book.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l1Z3B9tFSIfPMGE0G9cc0qC-TrhVnlbY
"""

contact ={}

def display_contact():
  print("Name\t\tContact Number")
  for key in contact:
    print("{}\t\t{}".format(key,contact.get(key)))
while True:
  choice = int(input("1. Add new contact \n2. Search contact \n3.Display contact \n4 Edit contact \n5. Delete contact \n6.Exit "))
  if choice ==1:
    name = input("enter the contact name: ")
    phone = input ("enter the mobile number")
    contact[name]= phone
  elif choice ==2:
    search_name = input("enter the contact name: ")
    if search_name in contact:
      print(search_name,"contact number is",contact[search_name])
    else:
      print("Name is not found in contact book")
  elif choice ==3:
      if not contact:
        print("empty contact Book ")
      else:
        display_contact()
  elif choice ==4:
    edit_contact =input("Enter the contact to be edited ")
    if edit_contact in contact:
      phone = input("enter mobile number")
      contact[edit_contact]=phone
      print("contact updayted")
      display_contact()
    else:
      print("Name is not found in contact book")
  elif choice ==5:
    del_contact = input("Enter the contact to be deleted")
    if del_contact in contact:
      confirm= input("Do you want to delete this contact y/n? ")
      if confirm =='y' or confirm =='Y':
        contact.pop(del_contact)
      display_contact()
    else:
      print("Name is not found in contact book ")
  else:
      break